<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper">
            Appointment list page
        </span>    
    </h1>
</div>

<fieldset class="fieldset create info">
    <legend class="legend"><span>Information</span></legend><br>
    <table>
        <tr><td><b>Name</b></td>
            <td><b>Phone</b></td>
            <td><b>Email</b></td>
        <?php
        $appointList = $block->getAppointments();

        foreach ($appointList as $appoint) {
            echo "<tr><td>".$appoint->getName()."</td>".
            "<td>".$appoint->getPhone()."</td>".
            "<td>".$appoint->getEmail()."</td></tr>";
        }
        ?>
    </table>

</fieldset>



