<?php
$blockObj= $block->getLayout()->createBlock('Allure\User\Block\CustomerGroups');
$groups = $blockObj->getCustomerGroup();
?>

<div class="field group_id required">

    <label for="group_id" class="label">
    <span><?php  echo __('Select Your Group') ?></span>
    </label>
    <div class="control">
        <select name="group_id">
        <?php foreach ($groups as $key => $data) { ?>
        <option value="<?php echo $data['value'] ?>"><?php echo $data['label'] ?>"</option>
        <?php } ?>
        </select>
    </div>
</div>